# Generated by Django 6.0.3 on 2026-04-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='student',
            name='stream',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
