# Generated by Django 6.0.3 on 2026-04-12 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_fix_student_teacher_fk_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='term',
            field=models.CharField(blank=True, choices=[('FIRST_TERM', 'First Term'), ('SECOND_TERM', 'Second Term'), ('THIRD_TERM', 'Third Term')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='TopicPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('max_score', models.FloatField(default=100)),
                ('assessment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.subject')),
            ],
        ),
    ]
