from django.db.models import Avg, F
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from rest_framework import viewsets
from rest_framework.decorators import api_view, permission_classes
from rest_framework.exceptions import PermissionDenied
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from .models import Student, Subject, Exam, Attendance, Assignment, TopicPerformance
from .serializers import (
    StudentSerializer,
    SubjectSerializer,
    ExamSerializer,
    AttendanceSerializer,
    AssignmentSerializer,
    TopicPerformanceSerializer,
)
from datetime import datetime
from io import BytesIO

from openpyxl import Workbook
from openpyxl.styles import Font


def _is_admin_user(user):
    return bool(getattr(user, 'is_staff', False) or getattr(user, 'is_superuser', False))


def _student_queryset_for_user(user):
    return Student.objects.all() if _is_admin_user(user) else Student.objects.filter(teacher=user)


def _ensure_teacher_owns_student(student, teacher):
    if not _is_admin_user(teacher) and student.teacher_id != teacher.id:
        raise PermissionDenied('You can only manage data for your own students.')


def _style_header_row(sheet, row_number=1):
    for cell in sheet[row_number]:
        cell.font = Font(bold=True)


def _build_all_students_report(students, request_user):
    workbook = Workbook()
    sheet = workbook.active
    sheet.title = 'Student Summary'

    headers = [
        'Name',
        'Admission Number',
        'Class',
        'Stream',
        'Average Exam Score',
        'Attendance Rate %',
        'Average Assignment Score',
        'Total Exams',
        'Total Attendance Records',
        'Total Assignments',
        'Created At',
    ]
    sheet.append(headers)

    for student in students:
        exams = Exam.objects.filter(student=student)
        attendance = Attendance.objects.filter(student=student)
        assignments = Assignment.objects.filter(student=student)

        avg_exam = exams.aggregate(Avg('score'))['score__avg'] or 0
        present_days = attendance.filter(status='present').count()
        attendance_rate = (present_days / attendance.count() * 100) if attendance.count() > 0 else 0
        avg_assignment = assignments.aggregate(Avg('score'))['score__avg']

        sheet.append([
            student.name,
            student.admission_number,
            student.student_class,
            student.stream or '',
            round(avg_exam, 2),
            round(attendance_rate, 2),
            round(avg_assignment, 2) if avg_assignment is not None else '',
            exams.count(),
            attendance.count(),
            assignments.count(),
            student.created_at.strftime('%Y-%m-%d %H:%M:%S'),
        ])

    _style_header_row(sheet)

    meta = workbook.create_sheet('Report Info')
    meta.append(['Generated By', request_user.get_full_name() or request_user.username])
    meta.append(['Generated At', datetime.now().strftime('%Y-%m-%d %H:%M:%S')])
    meta.append(['Total Students', students.count()])
    _style_header_row(meta, 1)

    exams_sheet = workbook.create_sheet('Exams')
    exams_sheet.append(['Student', 'Admission Number', 'Subject', 'Score', 'Term', 'Exam Type', 'Date'])

    attendance_sheet = workbook.create_sheet('Attendance')
    attendance_sheet.append(['Student', 'Admission Number', 'Date', 'Status', 'Subject'])

    assignments_sheet = workbook.create_sheet('Assignments')
    assignments_sheet.append(['Student', 'Admission Number', 'Subject', 'Title', 'Score', 'Max Score', 'Due Date', 'Submission Date'])

    topic_sheet = workbook.create_sheet('Topic Performance')
    topic_sheet.append(['Student', 'Admission Number', 'Subject', 'Topic', 'Score', 'Max Score', 'Assessment Date'])

    for student in students:
        for exam in Exam.objects.filter(student=student).select_related('subject'):
            exams_sheet.append([
                student.name,
                student.admission_number,
                exam.subject.name,
                exam.score,
                exam.get_term_display() if hasattr(exam, 'get_term_display') else exam.term,
                exam.exam_type,
                exam.date.strftime('%Y-%m-%d'),
            ])

        for record in Attendance.objects.filter(student=student).select_related('subject'):
            attendance_sheet.append([
                student.name,
                student.admission_number,
                record.date.strftime('%Y-%m-%d'),
                record.get_status_display() if hasattr(record, 'get_status_display') else record.status,
                record.subject.name if record.subject else 'N/A',
            ])

        for assignment in Assignment.objects.filter(student=student).select_related('subject'):
            assignments_sheet.append([
                student.name,
                student.admission_number,
                assignment.subject.name,
                assignment.title,
                assignment.score if assignment.score is not None else '',
                assignment.max_score,
                assignment.due_date.strftime('%Y-%m-%d'),
                assignment.submission_date.strftime('%Y-%m-%d') if assignment.submission_date else 'Not Submitted',
            ])

        for topic in TopicPerformance.objects.filter(student=student).select_related('subject'):
            topic_sheet.append([
                student.name,
                student.admission_number,
                topic.subject.name,
                topic.topic,
                topic.score,
                topic.max_score,
                topic.assessment_date.strftime('%Y-%m-%d'),
            ])

    for extra_sheet in (exams_sheet, attendance_sheet, assignments_sheet, topic_sheet):
        _style_header_row(extra_sheet)

    return workbook


def _build_student_report(student):
    workbook = Workbook()

    # Calculate performance metrics for the summary sheet
    exams = Exam.objects.filter(student=student).select_related('subject')
    attendance = Attendance.objects.filter(student=student)
    assignments = Assignment.objects.filter(student=student)
    
    avg_exam = exams.aggregate(Avg('score'))['score__avg'] or 0
    total_days = attendance.count()
    present_days = attendance.filter(status='present').count()
    attendance_rate = (present_days / total_days) if total_days > 0 else 0
    
    total_assignments = assignments.count()
    submitted_assignments = assignments.filter(submission_date__isnull=False).count()
    assignment_completion_rate = (submitted_assignments / total_assignments) if total_assignments > 0 else 0
    avg_assignment_score = assignments.aggregate(Avg('score'))['score__avg'] or 0
    
    # Calculate risk level and risk score
    risk_score = 0
    if avg_exam < 50:
        risk_score += 3
    elif avg_exam < 65:
        risk_score += 2
    elif avg_exam < 75:
        risk_score += 1
    
    if attendance_rate < 0.7:
        risk_score += 3
    elif attendance_rate < 0.85:
        risk_score += 2
    elif attendance_rate < 0.95:
        risk_score += 1
    
    if assignment_completion_rate < 0.6:
        risk_score += 3
    elif assignment_completion_rate < 0.8:
        risk_score += 2
    elif assignment_completion_rate < 0.95:
        risk_score += 1
    
    # Determine risk level based on risk score
    if risk_score >= 7:
        risk_level = 'HIGH'
    elif risk_score >= 4:
        risk_level = 'MODERATE'
    else:
        risk_level = 'LOW'
    
    # Performance Summary Sheet
    summary_sheet = workbook.active
    summary_sheet.title = 'Performance Summary'
    summary_sheet.append(['STUDENT PERFORMANCE SUMMARY'])
    summary_sheet.append([''])
    summary_sheet.append(['Student Information'])
    summary_sheet.append(['Name', student.name])
    summary_sheet.append(['Admission Number', student.admission_number])
    summary_sheet.append(['Class', student.student_class])
    summary_sheet.append(['Stream', student.stream or 'N/A'])
    summary_sheet.append([''])
    summary_sheet.append(['Overall Performance Metrics'])
    summary_sheet.append(['Average Exam Score', f'{round(avg_exam, 2)}%' if avg_exam else 'No data'])
    summary_sheet.append(['Attendance Rate', f'{round(attendance_rate * 100, 2)}%'])
    summary_sheet.append(['Assignment Completion Rate', f'{round(assignment_completion_rate * 100, 2)}%'])
    summary_sheet.append(['Average Assignment Score', f'{round(avg_assignment_score, 2)}%' if avg_assignment_score else 'No data'])
    summary_sheet.append([''])
    summary_sheet.append(['Risk Assessment'])
    summary_sheet.append(['Risk Level', risk_level])
    summary_sheet.append(['Risk Score', f'{risk_score}/13'])
    summary_sheet.append(['Status', 'At Risk' if risk_score >= 4 else 'Performing Well'])
    summary_sheet.append([''])
    summary_sheet.append(['Summary Statistics'])
    summary_sheet.append(['Total Exams Taken', exams.count()])
    summary_sheet.append(['Total Attendance Records', total_days])
    summary_sheet.append(['Present Days', present_days])
    summary_sheet.append(['Total Assignments', total_assignments])
    summary_sheet.append(['Submitted Assignments', submitted_assignments])
    summary_sheet.append(['Report Generated', datetime.now().strftime('%Y-%m-%d %H:%M:%S')])
    _style_header_row(summary_sheet, 1)

    info_sheet = workbook.create_sheet('Student Info')
    info_sheet.append(['Field', 'Value'])
    info_sheet.append(['Name', student.name])
    info_sheet.append(['Admission Number', student.admission_number])
    info_sheet.append(['Class', student.student_class])
    info_sheet.append(['Stream', student.stream or 'N/A'])
    info_sheet.append(['Created At', student.created_at.strftime('%Y-%m-%d %H:%M:%S')])
    _style_header_row(info_sheet)

    exams_sheet = workbook.create_sheet('Exams')
    exams_sheet.append(['Subject', 'Score', 'Term', 'Exam Type', 'Date'])
    for exam in exams.select_related('subject'):
        exams_sheet.append([
            exam.subject.name,
            exam.score,
            exam.get_term_display() if hasattr(exam, 'get_term_display') else exam.term,
            exam.exam_type,
            exam.date.strftime('%Y-%m-%d'),
        ])
    _style_header_row(exams_sheet)

    attendance_sheet = workbook.create_sheet('Attendance')
    attendance_sheet.append(['Date', 'Status', 'Subject'])
    for record in attendance.select_related('subject'):
        attendance_sheet.append([
            record.date.strftime('%Y-%m-%d'),
            record.get_status_display() if hasattr(record, 'get_status_display') else record.status,
            record.subject.name if record.subject else 'N/A',
        ])
    _style_header_row(attendance_sheet)

    assignments_sheet = workbook.create_sheet('Assignments')
    assignments_sheet.append(['Subject', 'Title', 'Score', 'Max Score', 'Due Date', 'Submission Date'])
    for assignment in assignments.select_related('subject'):
        assignments_sheet.append([
            assignment.subject.name,
            assignment.title,
            assignment.score if assignment.score is not None else '',
            assignment.max_score,
            assignment.due_date.strftime('%Y-%m-%d'),
            assignment.submission_date.strftime('%Y-%m-%d') if assignment.submission_date else 'Not Submitted',
        ])
    _style_header_row(assignments_sheet)

    topic_sheet = workbook.create_sheet('Topic Performance')
    topic_sheet.append(['Subject', 'Topic', 'Score', 'Max Score', 'Assessment Date'])
    for topic in TopicPerformance.objects.filter(student=student).select_related('subject'):
        topic_sheet.append([
            topic.subject.name,
            topic.topic,
            topic.score,
            topic.max_score,
            topic.assessment_date.strftime('%Y-%m-%d'),
        ])
    _style_header_row(topic_sheet)

    return workbook


def _workbook_response(workbook, file_name):
    output = BytesIO()
    workbook.save(output)
    output.seek(0)
    response = HttpResponse(
        output.getvalue(),
        content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    )
    response['Content-Disposition'] = f'attachment; filename="{file_name}"'
    return response

class StudentViewSet(viewsets.ModelViewSet):
    serializer_class = StudentSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        # Teachers only see their own students; admins see all students.
        return _student_queryset_for_user(self.request.user)

    def perform_create(self, serializer):
        # Teachers are auto-assigned to their students; admins can optionally set a teacher.
        if _is_admin_user(self.request.user):
            serializer.save(teacher=serializer.validated_data.get('teacher', self.request.user))
        else:
            serializer.save(teacher=self.request.user)

class SubjectViewSet(viewsets.ModelViewSet):
    queryset = Subject.objects.all()
    serializer_class = SubjectSerializer
    permission_classes = [IsAuthenticated]

class ExamViewSet(viewsets.ModelViewSet):
    serializer_class = ExamSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        # Teachers only see their own students' exams; admins see all exams.
        return Exam.objects.all() if _is_admin_user(self.request.user) else Exam.objects.filter(student__teacher=self.request.user)

    def perform_create(self, serializer):
        student = serializer.validated_data['student']
        _ensure_teacher_owns_student(student, self.request.user)
        serializer.save()

class AttendanceViewSet(viewsets.ModelViewSet):
    serializer_class = AttendanceSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        # Teachers only see their own students' attendance; admins see all attendance.
        return Attendance.objects.all() if _is_admin_user(self.request.user) else Attendance.objects.filter(student__teacher=self.request.user)

    def perform_create(self, serializer):
        student = serializer.validated_data['student']
        _ensure_teacher_owns_student(student, self.request.user)
        serializer.save()

class AssignmentViewSet(viewsets.ModelViewSet):
    serializer_class = AssignmentSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        # Teachers only see their own students' assignments; admins see all assignments.
        return Assignment.objects.all() if _is_admin_user(self.request.user) else Assignment.objects.filter(student__teacher=self.request.user)

    def perform_create(self, serializer):
        student = serializer.validated_data['student']
        _ensure_teacher_owns_student(student, self.request.user)
        serializer.save()


class TopicPerformanceViewSet(viewsets.ModelViewSet):
    serializer_class = TopicPerformanceSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        return TopicPerformance.objects.all() if _is_admin_user(self.request.user) else TopicPerformance.objects.filter(student__teacher=self.request.user)

    def perform_create(self, serializer):
        student = serializer.validated_data['student']
        _ensure_teacher_owns_student(student, self.request.user)
        serializer.save()


@api_view(["GET"])
@permission_classes([IsAuthenticated])
def student_insights(request, student_id):
    student = get_object_or_404(Student, id=student_id)
    _ensure_teacher_owns_student(student, request.user)

    exams = Exam.objects.filter(student=student).select_related('subject')
    attendance = Attendance.objects.filter(student=student).select_related('subject')
    assignments = Assignment.objects.filter(student=student).select_related('subject')
    topic_scores = TopicPerformance.objects.filter(student=student).select_related('subject')

    term_config = [
        ('FIRST_TERM', 'First Term'),
        ('SECOND_TERM', 'Second Term'),
        ('THIRD_TERM', 'Third Term'),
    ]
    term_performance = []
    for term_code, term_label in term_config:
        term_exams = exams.filter(term=term_code)
        subject_breakdown = []
        for subject_name in sorted({exam.subject.name for exam in term_exams}):
            subject_exams = term_exams.filter(subject__name=subject_name)
            subject_avg = subject_exams.aggregate(Avg('score'))['score__avg'] or 0
            subject_breakdown.append({
                'subject': subject_name,
                'average_score': round(subject_avg, 2),
                'exam_count': subject_exams.count(),
            })

        avg_score = term_exams.aggregate(Avg('score'))['score__avg']
        term_performance.append({
            'term': term_label,
            'average_score': round(avg_score, 2) if avg_score is not None else None,
            'exam_count': term_exams.count(),
            'subject_breakdown': subject_breakdown,
        })

    total_days = attendance.count()
    present_days = attendance.filter(status='present').count()
    late_days = attendance.filter(status='late').count()
    absent_days = attendance.filter(status='absent').count()
    attendance_rate = (present_days / total_days) if total_days else 0

    attendance_by_subject = []
    for subject_name in sorted({item.subject.name for item in attendance if item.subject_id}):
        rows = attendance.filter(subject__name=subject_name)
        subject_total = rows.count()
        subject_present = rows.filter(status='present').count()
        attendance_by_subject.append({
            'subject': subject_name,
            'attendance_rate': round((subject_present / subject_total), 2) if subject_total else 0,
            'total_lessons': subject_total,
        })

    total_assignments = assignments.count()
    submitted_assignments = assignments.filter(submission_date__isnull=False).count()
    late_submissions = assignments.filter(submission_date__isnull=False, submission_date__gt=F('due_date')).count()
    completion_rate = (submitted_assignments / total_assignments) if total_assignments else 0
    late_rate = (late_submissions / submitted_assignments) if submitted_assignments else 0
    assignment_avg = assignments.aggregate(Avg('score'))['score__avg']

    subject_summary = []
    for subject_name in sorted({exam.subject.name for exam in exams}):
        subject_exams = exams.filter(subject__name=subject_name)
        subject_avg = subject_exams.aggregate(Avg('score'))['score__avg'] or 0
        subject_summary.append({
            'subject': subject_name,
            'average_score': round(subject_avg, 2),
            'risk_level': 'high' if subject_avg < 50 else 'moderate' if subject_avg < 65 else 'low',
        })

    weak_subjects = [item for item in subject_summary if item['average_score'] < 60]

    topic_summary = []
    
    # Add weak topics from TopicPerformance records
    for row in topic_scores:
        percentage = (row.score / row.max_score) * 100 if row.max_score else 0
        topic_summary.append({
            'subject': row.subject.name,
            'topic': row.topic,
            'score_percentage': round(percentage, 2),
            'assessment_date': row.assessment_date,
            'source': 'assessment',
        })
    
    # Add weak topics from Assignment performance (per subject+topic)
    assignment_topic_stats = {}
    for assignment in assignments.select_related('subject'):
        if assignment.topic and assignment.score is not None:
            key = (assignment.subject.name, assignment.topic)
            if key not in assignment_topic_stats:
                assignment_topic_stats[key] = {'scores': [], 'max_scores': []}
            assignment_topic_stats[key]['scores'].append(assignment.score)
            assignment_topic_stats[key]['max_scores'].append(assignment.max_score)
    
    for (subject_name, topic_name), stats in assignment_topic_stats.items():
        avg_score = sum(stats['scores']) / len(stats['scores']) if stats['scores'] else 0
        avg_max_score = sum(stats['max_scores']) / len(stats['max_scores']) if stats['max_scores'] else 100
        percentage = (avg_score / avg_max_score) * 100 if avg_max_score else 0
        topic_summary.append({
            'subject': subject_name,
            'topic': topic_name,
            'score_percentage': round(percentage, 2),
            'assessment_date': None,
            'source': 'assignment',
        })
    
    topic_summary.sort(key=lambda x: x['score_percentage'])
    weak_topics = [row for row in topic_summary if row['score_percentage'] < 60]

    return Response({
        'student': {
            'id': student.id,
            'name': student.name,
            'admission_number': student.admission_number,
            'student_class': student.student_class,
            'stream': student.stream,
        },
        'term_performance': term_performance,
        'attendance': {
            'total_days': total_days,
            'present_days': present_days,
            'late_days': late_days,
            'absent_days': absent_days,
            'attendance_rate': round(attendance_rate, 2),
            'by_subject': attendance_by_subject,
        },
        'assignments': {
            'total': total_assignments,
            'submitted': submitted_assignments,
            'completion_rate': round(completion_rate, 2),
            'late_submission_rate': round(late_rate, 2),
            'average_score': round(assignment_avg, 2) if assignment_avg is not None else None,
        },
        'weak_subjects': weak_subjects,
        'weak_topics': weak_topics,
    })

@api_view(["GET"])
@permission_classes([IsAuthenticated])
def at_risk_students(request):
    # Teachers only get their own students; admins can view the whole school.
    students = _student_queryset_for_user(request.user)
    if not students.exists():
        return Response({
            "message": "No students in database yet.",
            "at_risk_students": [],
            "all_students": [],
        })

    results = []
    for student in students:
        exams = Exam.objects.filter(student=student)
        attendance = Attendance.objects.filter(student=student)
        assignments = Assignment.objects.filter(student=student)

        avg_exam = exams.aggregate(Avg("score"))["score__avg"] or 0
        total_days = attendance.count()
        present_days = attendance.filter(status="present").count()
        attendance_rate = present_days / total_days if total_days > 0 else 0

        total_assignments = assignments.count()
        submitted_assignments = assignments.filter(submission_date__isnull=False).count()
        assignment_completion_rate = submitted_assignments / total_assignments if total_assignments > 0 else 0
        avg_assignment_score = assignments.aggregate(Avg("score"))["score__avg"] or 0

        risk_score = 0
        if avg_exam < 50:
            risk_score += 1
        if attendance_rate < 0.8:
            risk_score += 1
        if assignment_completion_rate < 0.7:
            risk_score += 1

        at_risk = risk_score >= 1

        results.append({
            "student_id": student.id,
            "name": student.name,
            "avg_exam_score": round(avg_exam, 2),
            "attendance_rate": round(attendance_rate, 2),
            "assignment_completion_rate": round(assignment_completion_rate, 2),
            "avg_assignment_score": round(avg_assignment_score, 2),
            "risk_score": risk_score,
            "at_risk": at_risk,
        })

    at_risk_list = [r for r in results if r["at_risk"]]
    return Response({"at_risk_students": at_risk_list, "all_students": results})


@api_view(["GET"])
@permission_classes([IsAuthenticated])
def export_students_data(request):
    """Export all student data for the teacher as an Excel workbook."""
    students = _student_queryset_for_user(request.user)
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    workbook = _build_all_students_report(students, request.user)
    return _workbook_response(workbook, f'students_report_{timestamp}.xlsx')


@api_view(["GET"])
@permission_classes([IsAuthenticated])
def export_student_details(request, student_id):
    """Export detailed data for a specific student as an Excel workbook."""
    student = get_object_or_404(Student, id=student_id)
    _ensure_teacher_owns_student(student, request.user)
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    workbook = _build_student_report(student)
    return _workbook_response(workbook, f'{student.admission_number}_report_{timestamp}.xlsx')